# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.10.0'
    - name: Install Script
      run: ./install-linux-x86_64.sh
    - name: Build
      if: always()
      run: ./export-linux-x86_64.sh
    - name: Run tests
      run: swift test -v
    - uses: actions/upload-artifact@v4
      with:
        path: ./Godot/bin/debug/Linux/x86_64
